# Generated by Django 5.0.2 on 2025-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0003_alumnos_creation_alumnos_curp_alumnos_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('publico', models.TextField(blank=True, max_length=255, null=True)),
                ('programa', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('cupo_max', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='id_trabajador',
        ),
        migrations.AddField(
            model_name='maestros',
            name='id_maestro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
