# Generated by Django 5.0.2 on 2025-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0004_eventos_remove_maestros_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='id_maestro',
            new_name='id_trabajador',
        ),
        migrations.AddField(
            model_name='maestros',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
