# Generated by Django 5.0.2 on 2025-05-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0005_rename_id_maestro_maestros_id_trabajador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='responsable',
            new_name='responsable_id',
        ),
    ]
