# Generated by Django 5.0.2 on 2025-05-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0006_rename_responsable_eventos_responsable_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
    ]
